import React, {createContext, useState} from "react";

export const MainDataContext = createContext();

const MainDataContextProvider = (props) => {
    const [obj, setObj] = useState({
        "location": {
            "name": "Aerometre",
            "region": "Magallanes y de la Antartica Chilena",
            "country": "Chile",
            "lat": -53.75,
            "lon": -69.22,
            "tz_id": "America/Punta_Arenas",
            "localtime_epoch": 1652190121,
            "localtime": "Powered by weatherAPI"
        },
        "current": {
            "last_updated_epoch": 1652189400,
            "last_updated": "2022-05-10 10:30",
            "temp_c": "-",
            "temp_f": 39.4,
            "is_day": 2,
            "condition": {
                "text": "-",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 0
            },
            "wind_mph": 5.1,
            "wind_kph": "-",
            "wind_degree": 300,
            "wind_dir": "-",
            "pressure_mb": "-",
            "pressure_in": 30.0,
            "precip_mm": "-",
            "precip_in": 0.0,
            "humidity": "-",
            "cloud": "-",
            "feelslike_c": "-",
            "feelslike_f": 35.6,
            "vis_km": "-",
            "vis_miles": 6.0,
            "uv": "-",
            "gust_mph": 8.3,
            "gust_kph": "-",
            "air_quality": {
                "co": "-",
                "no2": "-",
                "o3": "-",
                "so2": "-",
                "pm2_5": "-",
                "pm10": 2.0999999046325684,
                "us-epa-index": 1,
                "gb-defra-index": 1
            }
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2022-05-10",
                    "date_epoch": 1652140800,
                    "day": {
                        "maxtemp_c": "-",
                        "maxtemp_f": 45.9,
                        "mintemp_c": "-",
                        "mintemp_f": 37.2,
                        "avgtemp_c": "-",
                        "avgtemp_f": 41.8,
                        "maxwind_mph": 11.0,
                        "maxwind_kph": "-",
                        "totalprecip_mm": "-",
                        "totalprecip_in": 0.0,
                        "avgvis_km": "-",
                        "avgvis_miles": 6.0,
                        "avghumidity": "-",
                        "daily_will_it_rain": 0,
                        "daily_chance_of_rain": 0,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "uv": 1.0
                    },
                    "astro": {
                        "sunrise": "-",
                        "sunset": "-",
                        "moonrise": "-",
                        "moonset": "-",
                        "moon_phase": "-",
                        "moon_illumination": "-"
                    },
                    "hour": [
                        {
                            "time_epoch": 1652151600,
                            "time": "2022-05-10 00:00",
                            "temp_c": 3.2,
                            "temp_f": 37.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.4,
                            "wind_kph": 15.1,
                            "wind_degree": 274,
                            "wind_dir": "W",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 85,
                            "cloud": 11,
                            "feelslike_c": -0.5,
                            "feelslike_f": 31.1,
                            "windchill_c": -0.5,
                            "windchill_f": 31.1,
                            "heatindex_c": 3.2,
                            "heatindex_f": 37.8,
                            "dewpoint_c": 1.0,
                            "dewpoint_f": 33.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.7,
                            "gust_kph": 28.4,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652155200,
                            "time": "2022-05-10 01:00",
                            "temp_c": 2.9,
                            "temp_f": 37.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 8.9,
                            "wind_kph": 14.4,
                            "wind_degree": 273,
                            "wind_dir": "W",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 86,
                            "cloud": 22,
                            "feelslike_c": -0.7,
                            "feelslike_f": 30.7,
                            "windchill_c": -0.7,
                            "windchill_f": 30.7,
                            "heatindex_c": 2.9,
                            "heatindex_f": 37.2,
                            "dewpoint_c": 0.8,
                            "dewpoint_f": 33.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.4,
                            "gust_kph": 28.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652158800,
                            "time": "2022-05-10 02:00",
                            "temp_c": 3.1,
                            "temp_f": 37.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 8.7,
                            "wind_kph": 14.0,
                            "wind_degree": 280,
                            "wind_dir": "W",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.97,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 84,
                            "cloud": 13,
                            "feelslike_c": -0.4,
                            "feelslike_f": 31.3,
                            "windchill_c": -0.4,
                            "windchill_f": 31.3,
                            "heatindex_c": 3.1,
                            "heatindex_f": 37.6,
                            "dewpoint_c": 0.6,
                            "dewpoint_f": 33.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.0,
                            "gust_kph": 27.4,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652162400,
                            "time": "2022-05-10 03:00",
                            "temp_c": 3.5,
                            "temp_f": 38.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 8.7,
                            "wind_kph": 14.0,
                            "wind_degree": 279,
                            "wind_dir": "W",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.97,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 80,
                            "cloud": 27,
                            "feelslike_c": 0.1,
                            "feelslike_f": 32.2,
                            "windchill_c": 0.1,
                            "windchill_f": 32.2,
                            "heatindex_c": 3.5,
                            "heatindex_f": 38.3,
                            "dewpoint_c": 0.4,
                            "dewpoint_f": 32.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 16.8,
                            "gust_kph": 27.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652166000,
                            "time": "2022-05-10 04:00",
                            "temp_c": 3.4,
                            "temp_f": 38.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 282,
                            "wind_dir": "WNW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.97,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 80,
                            "cloud": 32,
                            "feelslike_c": 0.2,
                            "feelslike_f": 32.4,
                            "windchill_c": 0.2,
                            "windchill_f": 32.4,
                            "heatindex_c": 3.4,
                            "heatindex_f": 38.1,
                            "dewpoint_c": 0.2,
                            "dewpoint_f": 32.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.2,
                            "gust_kph": 24.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652169600,
                            "time": "2022-05-10 05:00",
                            "temp_c": 3.4,
                            "temp_f": 38.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 7.2,
                            "wind_kph": 11.5,
                            "wind_degree": 289,
                            "wind_dir": "WNW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 81,
                            "cloud": 61,
                            "feelslike_c": 0.4,
                            "feelslike_f": 32.7,
                            "windchill_c": 0.4,
                            "windchill_f": 32.7,
                            "heatindex_c": 3.4,
                            "heatindex_f": 38.1,
                            "dewpoint_c": 0.5,
                            "dewpoint_f": 32.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.6,
                            "gust_kph": 22.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652173200,
                            "time": "2022-05-10 06:00",
                            "temp_c": 3.4,
                            "temp_f": 38.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 6.3,
                            "wind_kph": 10.1,
                            "wind_degree": 300,
                            "wind_dir": "WNW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 83,
                            "cloud": 100,
                            "feelslike_c": 0.7,
                            "feelslike_f": 33.3,
                            "windchill_c": 0.7,
                            "windchill_f": 33.3,
                            "heatindex_c": 3.4,
                            "heatindex_f": 38.1,
                            "dewpoint_c": 0.8,
                            "dewpoint_f": 33.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.6,
                            "gust_kph": 18.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652176800,
                            "time": "2022-05-10 07:00",
                            "temp_c": 3.4,
                            "temp_f": 38.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 6.3,
                            "wind_kph": 10.1,
                            "wind_degree": 311,
                            "wind_dir": "NW",
                            "pressure_mb": 1016.0,
                            "pressure_in": 29.99,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 84,
                            "cloud": 95,
                            "feelslike_c": 0.7,
                            "feelslike_f": 33.3,
                            "windchill_c": 0.7,
                            "windchill_f": 33.3,
                            "heatindex_c": 3.4,
                            "heatindex_f": 38.1,
                            "dewpoint_c": 1.0,
                            "dewpoint_f": 33.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.4,
                            "gust_kph": 18.4,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652180400,
                            "time": "2022-05-10 08:00",
                            "temp_c": 3.7,
                            "temp_f": 38.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 6.0,
                            "wind_kph": 9.7,
                            "wind_degree": 306,
                            "wind_dir": "NW",
                            "pressure_mb": 1016.0,
                            "pressure_in": 29.99,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 87,
                            "cloud": 30,
                            "feelslike_c": 1.2,
                            "feelslike_f": 34.2,
                            "windchill_c": 1.2,
                            "windchill_f": 34.2,
                            "heatindex_c": 3.7,
                            "heatindex_f": 38.7,
                            "dewpoint_c": 1.7,
                            "dewpoint_f": 35.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.1,
                            "gust_kph": 16.2,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652184000,
                            "time": "2022-05-10 09:00",
                            "temp_c": 4.1,
                            "temp_f": 39.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 5.1,
                            "wind_kph": 8.3,
                            "wind_degree": 300,
                            "wind_dir": "WNW",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.0,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 87,
                            "cloud": 48,
                            "feelslike_c": 2.0,
                            "feelslike_f": 35.6,
                            "windchill_c": 2.0,
                            "windchill_f": 35.6,
                            "heatindex_c": 4.1,
                            "heatindex_f": 39.4,
                            "dewpoint_c": 2.2,
                            "dewpoint_f": 36.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.3,
                            "gust_kph": 13.3,
                            "uv": 2.0
                        },
                        {
                            "time_epoch": 1652187600,
                            "time": "2022-05-10 10:00",
                            "temp_c": 5.2,
                            "temp_f": 41.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 6.7,
                            "wind_kph": 10.8,
                            "wind_degree": 299,
                            "wind_dir": "WNW",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.0,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 83,
                            "cloud": 47,
                            "feelslike_c": 2.7,
                            "feelslike_f": 36.9,
                            "windchill_c": 2.7,
                            "windchill_f": 36.9,
                            "heatindex_c": 5.2,
                            "heatindex_f": 41.4,
                            "dewpoint_c": 2.6,
                            "dewpoint_f": 36.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.8,
                            "gust_kph": 15.8,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1652191200,
                            "time": "2022-05-10 11:00",
                            "temp_c": 6.6,
                            "temp_f": 43.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 8.7,
                            "wind_kph": 14.0,
                            "wind_degree": 297,
                            "wind_dir": "WNW",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.0,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 78,
                            "cloud": 33,
                            "feelslike_c": 3.9,
                            "feelslike_f": 39.0,
                            "windchill_c": 3.9,
                            "windchill_f": 39.0,
                            "heatindex_c": 6.6,
                            "heatindex_f": 43.9,
                            "dewpoint_c": 3.0,
                            "dewpoint_f": 37.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.0,
                            "gust_kph": 17.6,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1652194800,
                            "time": "2022-05-10 12:00",
                            "temp_c": 7.3,
                            "temp_f": 45.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 293,
                            "wind_dir": "WNW",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.0,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 74,
                            "cloud": 32,
                            "feelslike_c": 4.5,
                            "feelslike_f": 40.1,
                            "windchill_c": 4.5,
                            "windchill_f": 40.1,
                            "heatindex_c": 7.3,
                            "heatindex_f": 45.1,
                            "dewpoint_c": 2.9,
                            "dewpoint_f": 37.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.9,
                            "gust_kph": 19.1,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1652198400,
                            "time": "2022-05-10 13:00",
                            "temp_c": 7.6,
                            "temp_f": 45.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 295,
                            "wind_dir": "WNW",
                            "pressure_mb": 1016.0,
                            "pressure_in": 29.99,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 71,
                            "cloud": 46,
                            "feelslike_c": 4.8,
                            "feelslike_f": 40.6,
                            "windchill_c": 4.8,
                            "windchill_f": 40.6,
                            "heatindex_c": 7.6,
                            "heatindex_f": 45.7,
                            "dewpoint_c": 2.8,
                            "dewpoint_f": 37.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.9,
                            "gust_kph": 19.1,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1652202000,
                            "time": "2022-05-10 14:00",
                            "temp_c": 7.7,
                            "temp_f": 45.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 301,
                            "wind_dir": "WNW",
                            "pressure_mb": 1016.0,
                            "pressure_in": 29.99,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 71,
                            "cloud": 44,
                            "feelslike_c": 5.0,
                            "feelslike_f": 41.0,
                            "windchill_c": 5.0,
                            "windchill_f": 41.0,
                            "heatindex_c": 7.7,
                            "heatindex_f": 45.9,
                            "dewpoint_c": 2.9,
                            "dewpoint_f": 37.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.9,
                            "gust_kph": 19.1,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1652205600,
                            "time": "2022-05-10 15:00",
                            "temp_c": 7.6,
                            "temp_f": 45.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 9.2,
                            "wind_kph": 14.8,
                            "wind_degree": 307,
                            "wind_dir": "NW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 73,
                            "cloud": 44,
                            "feelslike_c": 5.0,
                            "feelslike_f": 41.0,
                            "windchill_c": 5.0,
                            "windchill_f": 41.0,
                            "heatindex_c": 7.6,
                            "heatindex_f": 45.7,
                            "dewpoint_c": 3.1,
                            "dewpoint_f": 37.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.1,
                            "gust_kph": 19.4,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1652209200,
                            "time": "2022-05-10 16:00",
                            "temp_c": 7.4,
                            "temp_f": 45.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 316,
                            "wind_dir": "NW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 74,
                            "cloud": 48,
                            "feelslike_c": 4.6,
                            "feelslike_f": 40.3,
                            "windchill_c": 4.6,
                            "windchill_f": 40.3,
                            "heatindex_c": 7.4,
                            "heatindex_f": 45.3,
                            "dewpoint_c": 3.2,
                            "dewpoint_f": 37.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.6,
                            "gust_kph": 22.0,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1652212800,
                            "time": "2022-05-10 17:00",
                            "temp_c": 7.2,
                            "temp_f": 45.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 323,
                            "wind_dir": "NW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 75,
                            "cloud": 68,
                            "feelslike_c": 4.3,
                            "feelslike_f": 39.7,
                            "windchill_c": 4.3,
                            "windchill_f": 39.7,
                            "heatindex_c": 7.2,
                            "heatindex_f": 45.0,
                            "dewpoint_c": 3.0,
                            "dewpoint_f": 37.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.8,
                            "gust_kph": 23.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652216400,
                            "time": "2022-05-10 18:00",
                            "temp_c": 6.5,
                            "temp_f": 43.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 10.1,
                            "wind_kph": 16.2,
                            "wind_degree": 328,
                            "wind_dir": "NNW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 73,
                            "cloud": 57,
                            "feelslike_c": 3.4,
                            "feelslike_f": 38.1,
                            "windchill_c": 3.4,
                            "windchill_f": 38.1,
                            "heatindex_c": 6.5,
                            "heatindex_f": 43.7,
                            "dewpoint_c": 2.0,
                            "dewpoint_f": 35.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.2,
                            "gust_kph": 27.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652220000,
                            "time": "2022-05-10 19:00",
                            "temp_c": 6.5,
                            "temp_f": 43.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 327,
                            "wind_dir": "NNW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 72,
                            "cloud": 100,
                            "feelslike_c": 3.5,
                            "feelslike_f": 38.3,
                            "windchill_c": 3.5,
                            "windchill_f": 38.3,
                            "heatindex_c": 6.5,
                            "heatindex_f": 43.7,
                            "dewpoint_c": 1.8,
                            "dewpoint_f": 35.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 16.8,
                            "gust_kph": 27.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652223600,
                            "time": "2022-05-10 20:00",
                            "temp_c": 6.6,
                            "temp_f": 43.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 11.0,
                            "wind_kph": 17.6,
                            "wind_degree": 329,
                            "wind_dir": "NNW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.97,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 70,
                            "cloud": 86,
                            "feelslike_c": 3.4,
                            "feelslike_f": 38.1,
                            "windchill_c": 3.4,
                            "windchill_f": 38.1,
                            "heatindex_c": 6.6,
                            "heatindex_f": 43.9,
                            "dewpoint_c": 1.5,
                            "dewpoint_f": 34.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 19.2,
                            "gust_kph": 31.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652227200,
                            "time": "2022-05-10 21:00",
                            "temp_c": 6.6,
                            "temp_f": 43.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 10.5,
                            "wind_kph": 16.9,
                            "wind_degree": 330,
                            "wind_dir": "NNW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 70,
                            "cloud": 92,
                            "feelslike_c": 3.5,
                            "feelslike_f": 38.3,
                            "windchill_c": 3.5,
                            "windchill_f": 38.3,
                            "heatindex_c": 6.6,
                            "heatindex_f": 43.9,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 18.8,
                            "gust_kph": 30.2,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652230800,
                            "time": "2022-05-10 22:00",
                            "temp_c": 6.9,
                            "temp_f": 44.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 10.3,
                            "wind_kph": 16.6,
                            "wind_degree": 334,
                            "wind_dir": "NNW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 69,
                            "cloud": 76,
                            "feelslike_c": 3.9,
                            "feelslike_f": 39.0,
                            "windchill_c": 3.9,
                            "windchill_f": 39.0,
                            "heatindex_c": 6.9,
                            "heatindex_f": 44.4,
                            "dewpoint_c": 1.7,
                            "dewpoint_f": 35.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 18.3,
                            "gust_kph": 29.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1652234400,
                            "time": "2022-05-10 23:00",
                            "temp_c": 7.1,
                            "temp_f": 44.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 10.1,
                            "wind_kph": 16.2,
                            "wind_degree": 337,
                            "wind_dir": "NNW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.94,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 69,
                            "cloud": 71,
                            "feelslike_c": 4.2,
                            "feelslike_f": 39.6,
                            "windchill_c": 4.2,
                            "windchill_f": 39.6,
                            "heatindex_c": 7.1,
                            "heatindex_f": 44.8,
                            "dewpoint_c": 1.8,
                            "dewpoint_f": 35.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.9,
                            "gust_kph": 28.8,
                            "uv": 1.0
                        }
                    ]
                }
            ]
        }
    });
    return(
        <MainDataContext.Provider value = {{obj, setObj}}>
            {props.children}
        </MainDataContext.Provider>
    )
}

export default MainDataContextProvider;